name: b2bcarrello

services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app:rw
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: library/postgres:11.12
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
