version: '3'

services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - MEMCACHED_URL=memcached://cache:11211
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
      - AWS_REGION_NAME=us-east-1
    volumes:
      - .:/app:rw
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
  db:
    image: library/postgres:11.12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  cache:
    image: memcached
    ports:
      - "11211:11211"
