# Generated by Django 3.2.25 on 2025-06-22 15:34

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0067_departament_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='banners/%Y/%m/%d/', verbose_name='image')),
                ('article', models.ForeignKey(help_text='Article that this banner links to', on_delete=django.db.models.deletion.CASCADE, to='commercial.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
